/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 giftBox.gltf
*/
import "../../src/index.css"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { Group } from 'three'

import "../../src/index.css";


const Boxes = (props) => {

  const { nodes, materials } = useGLTF('/giftBox.gltf')
  console.log(Group)
  return (
    <group className='z-10' {...props} dispose={null} scale={1} position={[9,1,1]}>
      <mesh geometry={nodes.Giftbox01.geometry} material={materials.Pink01} position={[0.001, 1.058, 0]} />
      <mesh geometry={nodes.Giftbox02.geometry} material={materials.Pink02} position={[0.001, 1.307, 0]} rotation={[0, Math.PI / 2, 0]} scale={1.026} />
      <mesh geometry={nodes.Giftbox03.geometry} material={materials.Pink02} position={[0.009, 2.189, 0]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.Giftbox04.geometry} material={materials.Pink03} position={[0.009, 2.189, 0]} rotation={[-0.051, 0, 0]} scale={[0.183, 0.403, 0.363]} />
      <mesh geometry={nodes.Giftbox05.geometry} material={materials.Pink01} position={[0.009, 2.189, 0]} />
      <mesh geometry={nodes.Giftbox06.geometry} material={materials.Yellow01} position={[0.003, 2.377, 0.007]} scale={0.168} />
    </group>
  )
}

useGLTF.preload('/giftBox.gltf')

export default Boxes